services:
  php-fpm:
    build:
      context: .
      dockerfile: build/test/Dockerfile
    volumes:
      - ./src:/app/src
    expose:
      - 9000

  nginx:
    build:
      context: .
      dockerfile: build/test/Dockerfile-nginx
    ports:
      - 443:443